dissred/content/urls.py
# urls.py
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('',
                       url(r'legal-advice/$',
                           legal_advice, name='legal_advice'),
                       url(r'privacy-policy/$',
                           privacy_policy, name='privacy_policy'),
                       url(r'cookies-policy/$',
                           cookies_policy, name='cookies_policy'),
                       url(r'$', home, name='home'),
                       )

dissred/dissred/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'dissred.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^email/', include(
                           'mailgun_incoming.urls',
                           namespace="mailgun_incoming")),
                       url(r'^', include('content.urls', namespace="content")),
                       )

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^media/(?P<path>.*)$',
                                'django.views.static.serve', {
                                'document_root':
                                settings.MEDIA_ROOT,
                                'show_indexes': True}),

                            )

dissred/content/models.py
from django.db import models

# Create your models here.

dissred/content/forms.py
# -*- coding: utf-8 -*-
from django import forms


class ContactForm(forms.Form):
    message = forms.CharField(required=False, widget=forms.Textarea(
        attrs={
            'placeholder':
            'Escribe tu mensaje, puedes pedir presupuesto sin compromiso'}),
        max_length=1000)
    email = forms.EmailField(required=False, max_length=100,
                             widget=forms.EmailInput(attrs={
                                                     'placeholder': 'Tu email'
                                                     }))
    phone = forms.CharField(required=False, max_length=12, min_length=9,
                            widget=forms.TextInput(
                                attrs={'placeholder': 'Tu número de teléfono'
                                       }))
    # phone = forms.IntegerField(required = False, \
    # widget=forms.NumberInput(attrs={
    # 'placeholder': 'Tu número de teléfono'}))

    def clean(self):
        if not (self.cleaned_data.get('message') or
                self.cleaned_data.get('email')
                or self.cleaned_data.get('phone')):
            raise forms.ValidationError(
                "¡¡ Por favor, indique al menos uno de los datos de contacto, \
                email o teléfono !!'")
        return self.cleaned_data

dissred/content/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from .forms import ContactForm
from django.core.mail import send_mail


def home(request):

    context = {}
    form = ContactForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            subject = 'Contact from Malagapresupuestosweb.com'
            message = form.cleaned_data['message'] or 'Sin mensaje...'
            sender = form.cleaned_data[
                'email'] or 'noemail@malagapresupuestos.com'
            phone = form.cleaned_data['phone']
            message = message + '\nTlf: ' + str(phone) + '\nEmail: ' + sender

            recipients = ['info@malagapresupuestosweb.com']

            send_mail(subject, message, sender, recipients)
            context[
                'message'] = '¡¡ Muchas gracias por contactar con \
                Malagapresupuestosweb.com !!'

    context['form'] = form

    # import pdb; pdb.set_trace()
    return render(request, 'home.html', context)


def legal_advice(request):
    return render(request, 'legal_advice.html', {})


def privacy_policy(request):
    return render(request, 'privacy_policy.html', {})


def cookies_policy(request):
    return render(request, 'cookies_policy.html', {})

dissred/content/templates/bottom.html
<!--Bottom-->
<section id="bottom" class="main">
    <!--Container-->
    <div class="container">

        <!--row-fluids-->
        <div class="row-fluid">

            <!--Contact Form-->
            <div class="span3">
                <h4>DIRECCIÓN</h4>
                <ul class="unstyled address">
                    <li>
                        <i class="icon-home"></i><strong>Dirección:</strong> Calle Poeta Aurora de Albornoz, 4<br>Málaga
                    </li>
                    <li>
                        <i class="icon-envelope"></i>
                        <strong>Email: </strong> info@malagapresupuestosweb.com
                    </li>
                    <li>
                        <i class="icon-globe"></i>
                        <strong>Website:</strong> www.malagapresupuestosweb.com
                    </li>
                    <li>
                        <i class="icon-phone"></i>
                        <strong>Teléfono:</strong> 655 47 10 58
                    </li>
                </ul>
            </div>
            <!--End Contact Form-->

            <!--Important Links
            <div id="tweets" class="span3">
                <h4>OUR COMPANY</h4>
                <div>
                    <ul class="arrow">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Support</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Copyright</a></li>
                        <li><a href="#">We are hiring</a></li>
                        <li><a href="#">Clients</a></li>
                        <li><a href="#">Blog</a></li>
                    </ul>
                </div>
            </div>-->
            <!--Important Links-->

            <!--Archives
            <div id="archives" class="span3">
                <h4>ARCHIVES</h4>
                <div>
                    <ul class="arrow">
                        <li><a href="#">December 2012 (1)</a></li>
                        <li><a href="#">November 2012 (5)</a></li>
                        <li><a href="#">October 2012 (8)</a></li>
                        <li><a href="#">September 2012 (10)</a></li>
                        <li><a href="#">August 2012 (29)</a></li>
                        <li><a href="#">July 2012 (1)</a></li>
                        <li><a href="#">June 2012 (31)</a></li>
                    </ul>
                </div>
            </div>-->
            <!--End Archives

            <div class="span3">
                <h4>FLICKR GALLERY</h4>
                <div class="row-fluid first">
                    <ul class="thumbnails">
                      <li class="span3">
                        <a href="http://www.flickr.com/photos/76029035@N02/6829540293/" title="01 (254) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7003/6829540293_bd99363818_s.jpg" width="75" height="75" alt="01 (254)"></a>
                    </li>
                    <li class="span3">
                        <a href="http://www.flickr.com/photos/76029035@N02/6829537417/" title="01 (196) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7013/6829537417_465d28e1db_s.jpg" width="75" height="75" alt="01 (196)"></a>
                    </li>
                    <li class="span3">
                        <a href="http://www.flickr.com/photos/76029035@N02/6829527437/" title="01 (65) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7021/6829527437_88364c7ec4_s.jpg" width="75" height="75" alt="01 (65)"></a>
                    </li>
                    <li class="span3">
                        <a href="http://www.flickr.com/photos/76029035@N02/6829524451/" title="01 (6) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7148/6829524451_a725793358_s.jpg" width="75" height="75" alt="01 (6)"></a>
                    </li>
                </ul>
            </div>
            <div class="row-fluid">
                <ul class="thumbnails">
                    <li class="span3">
                        <a href="http://www.flickr.com/photos/76029035@N02/6829524451/" title="01 (6) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7148/6829524451_a725793358_s.jpg" width="75" height="75" alt="01 (6)"></a>
                    </li>
                    <li class="span3">
                        <a href="http://www.flickr.com/photos/76029035@N02/6829540293/" title="01 (254) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7003/6829540293_bd99363818_s.jpg" width="75" height="75" alt="01 (254)"></a>
                    </li>
                    <li class="span3">
                        <a href="http://www.flickr.com/photos/76029035@N02/6829537417/" title="01 (196) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7013/6829537417_465d28e1db_s.jpg" width="75" height="75" alt="01 (196)"></a>
                    </li>
                    <li class="span3">
                        <a href="http://www.flickr.com/photos/76029035@N02/6829527437/" title="01 (65) by Victor1558, on Flickr"><img src="http://farm8.staticflickr.com/7021/6829527437_88364c7ec4_s.jpg" width="75" height="75" alt="01 (65)"></a>
                    </li>
                </ul>
            </div>

        </div>

    </div>-->
    <!--/row-fluid-->
</div>
<!--/container-->

</section>
<!--/bottom-->

dissred/content/templates/clients.html
<section id="clients" class="main">
    <div class="container">
        <div class="row-fluid">
            <div class="span2">
                <div class="clearfix">
                    <h4 class="pull-left">OUR PARTNERS</h4>
                    <div class="pull-right">
                        <a class="prev" href="#myCarousel" data-slide="prev"><i class="icon-angle-left icon-large"></i></a> <a class="next" href="#myCarousel" data-slide="next"><i class="icon-angle-right icon-large"></i></a>
                    </div>
                </div>
                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
            </div>
            <div class="span10">
                <div id="myCarousel" class="carousel slide clients">
                  <!-- Carousel items -->
                  <div class="carousel-inner">
                    <div class="active item">
                        <div class="row-fluid">
                            <ul class="thumbnails">
                                <li class="span3"><a href="#"><img src="images/sample/clients/client1.png"></a></li>
                                <li class="span3"><a href="#"><img src="images/sample/clients/client2.png"></a></li>
                                <li class="span3"><a href="#"><img src="images/sample/clients/client3.png"></a></li>
                                <li class="span3"><a href="#"><img src="images/sample/clients/client4.png"></a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="item">
                        <div class="row-fluid">
                            <ul class="thumbnails">
                                <li class="span3"><a href="#"><img src="images/sample/clients/client4.png"></a></li>
                                <li class="span3"><a href="#"><img src="images/sample/clients/client3.png"></a></li>
                                <li class="span3"><a href="#"><img src="images/sample/clients/client2.png"></a></li>
                                <li class="span3"><a href="#"><img src="images/sample/clients/client1.png"></a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="item">
                        <div class="row-fluid">
                            <ul class="thumbnails">
                                <li class="span3"><a href="#"><img src="images/sample/clients/client1.png"></a></li>
                                <li class="span3"><a href="#"><img src="images/sample/clients/client2.png"></a></li>
                                <li class="span3"><a href="#"><img src="images/sample/clients/client3.png"></a></li>
                                <li class="span3"><a href="#"><img src="images/sample/clients/client4.png"></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /Carousel items -->

            </div>
        </div>
    </div>
</div>
</section>

dissred/content/templates/cookies_policy.html
{% extends "layout.html" %}

{% block title %}Málaga Presupuestos Web: Política de Cookies{% endblock title %}

{% block content %}

    {% include "header.html" %}
    <section class="main-info">
        <div class="container">
            <div class="row-fluid">
                <div class="contenido-informativo">
                    <h1><strong>POLÍTICA DE COOKIES</strong></h1>

                    <h4>a) Utilización de Cookies y Web Bugs por las Webs de Antonio Ignacio Campos Ruiz</h4>
                    <h4>b) Tipología, finalidad y funcionamiento de las Cookies</h4>
                    <h4>c) Cómo deshabilitar las Cookies y los Web Bugs en los principales navegadores</h4>
                    <h4>d) Qué ocurre si se deshabilitan las Cookies</h4>

                    <p>&nbsp;</p>
                    <h4><strong>ACTUALIZACIONES Y CAMBIOS EN LA POLÍTICA DE PRIVACIDAD/COOKIES</strong></h4>

                    <p>&nbsp;</p>
                    <h3><strong>a) Utilización de Cookies y Web Bugs por las Webs de Antonio Ignacio Campos Ruiz:</strong></h3>

                    Las Webs de Antonio Ignacio Campos Ruiz (en adelante, AICR) utilizan ¨Cookies¨, y otros mecanismos similares (en adelante, Cookies). Las Cookies son ficheros enviados a un navegador por medio de un servidor web para registrar las actividades del Usuario en una web determinada o en todas las webs, apps y/o servicios de las Webs de AICR (en adelante, los Servicios). La primera finalidad de las Cookies es la de facilitar al Usuario un acceso más rápido a los Servicios seleccionados. Además, las Cookies personalizan los Servicios que ofrece las Webs de AICR, facilitando y ofreciendo a cada Usuario información que es de su interés o que puede ser de su interés, en atención al uso que realiza de los Servicios.
                    <br><br>
                    Las Webs de AICR utilizan Cookies para personalizar y facilitar al máximo la navegación del Usuario. Las Cookies se asocian únicamente a un Usuario anónimo y su ordenador y no proporcionan referencias que permitan deducir datos personales del Usuario. El Usuario podrá configurar su navegador para que notifique y rechace la instalación de las Cookies enviadas por las Webs de AICR, sin que ello perjudique la posibilidad del Usuario de acceder a los Contenidos. Sin embargo, le hacemos notar que, en todo caso, la calidad de funcionamiento de la página Web puede disminuir.
                    <br><br>
                    Los Usuarios registrados que se registren o que hayan iniciado sesión, podrán beneficiarse de unos servicios más personalizados y orientados a su perfil, gracias a la combinación de los datos almacenados en las cookies con los datos personales utilizados en el momento de su registro. Dichos Usuarios autorizan expresamente el uso de esta información con la finalidad indicada, sin perjuicio de su derecho a rechazar o deshabilitar el uso de cookies.
                    <br><br>
                    Asimismo, las Webs de AICR podrán saber todos los Servicios de AICR solicitados por los Usuarios, de forma que podrán facilitar u ofrecer información adecuada a los gustos y preferencias de cada Usuario.
                    <br><br>
                    Las Webs de AICR también utiliza Web Bugs, que son imágenes diminutas y transparentes insertas en los emails. Cuando el Usuario abre el email, esta imagen se descarga junto con el resto del contenido del email y permite conocer si un email concreto ha sido abierto o no, así como la dirección IP desde la que se ha descargado. Las Webs de AICR utilizan esta información para obtener estadísticas y poner realizar estudios analíticos sobre la recepción de sus emails por parte de los Usuarios.
                    <br><br>
                     <p>&nbsp;</p>
                    <h3><strong>b) Tipología, finalidad y funcionamiento de las Cookies:</strong></h3>

                    Las Cookies, en función de su permanencia, pueden dividirse en Cookies de sesión o permanentes. Las primeras expiran cuando el Usuario cierra el navegador. Las segundas expiran en función de cuando se cumpla el objetivo para el que sirven (por ejemplo, para que el Usuario se mantenga identificado en los Servicios de AICR) o bien cuando se borran manualmente.
                    Adicionalmente, en función de su objetivo, las Cookies puedes clasificarse de la siguiente forma:
                    <br>
                    COOKIES DE RENDIMIENTO: Este tipo de Cookie recuerda sus preferencias para las herramientas que se encuentran en los Servicios, por lo que no tiene que volver a configurar el servicio cada vez que usted la visita. A modo de ejemplo, en esta tipología se incluyen:
                    <ul>
                    <li>Ajustes de volumen de reproductores de vídeo o sonido.</li>
                    <li>Las velocidades de transmisión de vídeo que sean compatibles con su navegador.</li>
                    <li>Los objetos guardados en el “carrito de la compra” en los Servicios de e-commerce tales como tiendas.</li>
                    </ul>
                    <p>&nbsp;</p>
                    COOKIES DE GEO-LOCALIZACIÓN: Estas Cookies son utilizadas para averiguar en qué país se encuentra cuando se solicita un Servicio. Esta Cookie es totalmente anónima, y sólo se utiliza para ayudar a orientar el contenido a su ubicación.
                    <br>
                    COOKIES DE REGISTRO: Las Cookies de registro se generan una vez que el Usuario se ha registrado o posteriormente, cuando ha abierto su sesión, y se utilizan para identificarle en los Servicios con los siguientes objetivos:
                    <ul>
                    <li>Mantener al Usuario identificado de forma que, si cierra un Servicio, el navegador o el ordenador y en otro momento u otro día vuelve a entrar en dicho Servicio, seguirá identificado, facilitando así su navegación sin tener que volver a identificarse. Esta funcionalidad se puede suprimir si el Usuario pulsa la funcionalidad “cerrar sesión”, de forma que esta Cookie se elimina y la próxima vez que entre en el Servicio el Usuario tendrá que iniciar sesión para estar identificado.</li>
                    <li>Comprobar si el Usuario está autorizado para acceder a ciertos Servicios, por ejemplo, para participar en un concurso.</li>
                    </ul>
                    <p>&nbsp;</p>
                    Adicionalmente, algunos Servicios pueden utilizar conectores con redes sociales tales como Facebook o Twitter. Cuando el Usuario se registra en un Servicio con credenciales de una red social, autoriza a la red social a guardar una Cookie persistente que recuerda su identidad y le garantiza acceso a los Servicios hasta que expira. El Usuario puede borrar esta Cookie y revocar el acceso a los Servicios mediante redes sociales actualizando sus preferencias en la red social específica.
                    <br>
                    COOKIES DE ANALÍTICAS: Cada vez que un Usuario visita un Servicio, una herramienta de un proveedor externo (Omniture, Netscope, Comscore y similares podrán añadirse a este listado en caso de que varíen en relación con los actuales) genera una Cookie analítica en el ordenador del Usuario. Esta Cookie que sólo se genera en la visita, servirá en próximas visitas a los Servicios de AICR para identificar de forma anónima al visitante. Los objetivos principales que se persiguen son:
                    <ul style="margin-left: 20px; display: list-item">
                    <li>Permitir la identificación anónima de los Usuarios navegantes a través de la “Cookie” (identifica navegadores y dispositivos, no personas) y por lo tanto la contabilización aproximada del número de visitantes y su tendencia en el tiempo.</li>
                    Identificar de forma anónima los contenidos más visitados y por lo tanto más atractivos para los Usuarios
                    <li>Saber si el Usuario que está accediendo es nuevo o repite visita.</li>
                    </ul>
                    <p>&nbsp;</p>
                    <strong>Importante</strong>: Salvo que el Usuario decida registrarse en un Servicio de AICR, la “Cookie” nunca irá asociada a ningún dato de carácter personal que pueda identificarle. Dichas Cookies sólo serán utilizadas con propósitos estadísticos que ayuden a la optimización de la experiencia de los Usuarios en el sitio.
                    <br>
                    COOKIES DE PUBLICIDAD: Este tipo de “Cookies” permiten ampliar la información de los anuncios mostrados a cada Usuario anónimo en los Servicios de AICR. Entre otros, se almacena la duración o frecuencia de visualización de posiciones publicitarias, la interacción con las mismas, o los patrones de navegación y/o comportamientos del Usuario ya que ayudan a conformar un perfil de interés publicitario. De este modo, permiten ofrecer publicidad afín a los intereses del Usuario.
                    <br>
                    COOKIES PUBLICITARIAS DE TERCEROS: Además de la publicidad gestionada por las Webs de AICR en sus Servicios, las Webs de AICR pueden ofrecer a sus anunciantes la opción de servir anuncios a través de terceros (“Ad-Servers”). De este modo, estos terceros pueden almacenar Cookies enviadas desde los Servicios de AICR procedentes de los navegadores de los Usuarios, así como acceder a los datos que en ellas se guardan.
                    <br>
                    Las empresas que generan estas Cookies tienen sus propias políticas de privacidad. En la actualidad, las Webs de AICR no ofrecen este tipo de servicios. Para saber más sobre estos servicios de anuncios puede visitar la plataforma Doubleclick (Google). http://www.google.es/policies/privacy/ads/#toc-doubleclick y http://www.google.es/policies/privacy/ads/.

                    <br><br>
                    <p>&nbsp;</p>
                    <h3><strong>c) Cómo deshabilitar las Cookies y los Web Bugs en los principales navegadores:</strong></h3>

                    Normalmente es posible dejar de aceptar las Cookies del navegador, o dejar de aceptar las Cookies de un Servicio en particular.
                    Todos los navegadores modernos permiten cambiar la configuración de Cookies. Estos ajustes normalmente se encuentran en las ‘opciones’ o ‘Preferencias’ del menú de su navegador. Asimismo, puede configurar su navegador o su gestor de correo electrónico, así como instalar complementos gratuitos para evitar que se descarguen los Web Bugs al abrir un email.
                    <br><br>
                    Las Webs de AICR ofrecen orientación al Usuario sobre los pasos para acceder al menú de configuración de las cookies y, en su caso, de la navegación privada en cada uno de los navegadores principales:
                    <br><br>
                    <ul>
                    <li>Firefox: Herramientas -&gt; Opciones -&gt; Privacidad -&gt; Historial -&gt; Configuración Personalizada. Para más información, puede consultar el <a target="_blank" href="http://support.mozilla.org/es/home">soporte de Mozilla</a> o la Ayuda del navegador.</li>
                    <li>Chrome: Configuración -&gt; Mostrar opciones avanzadas -&gt; Privacidad -&gt; Configuración de contenido. Para más información, puede consultar el <a target="_blank" href="http://support.google.com/chrome/?hl=es">soporte de Google</a> o la Ayuda del navegador.</li>
                    <li>Internet Explorer: Herramientas -&gt; Opciones de Internet -&gt; Privacidad -&gt; Configuración. Para más información, puede consultar el <a target="_blank" href="http://windows.microsoft.com/es-ES/windows/support">soporte de Microsoft</a> o la Ayuda del navegador.</li>
                    <li>Safari: Preferencias -&gt; Seguridad. Para más información, puede consultar el <a target="_blank" href="http://www.apple.com/es/support/safari/">soporte de Apple</a> o la Ayuda del navegador.</li>
                    </ul>

                    <br>
                    <p>&nbsp;</p>
                    <h3><strong>d) Qué ocurre si se deshabilitan las Cookies:</strong></h3>

                    Algunas funcionalidades de los Servicios quedarán deshabilitados como, por ejemplo, permanecer  identificado, mantener las compras en el “carrito de la compra” en un Servicio de e-commerce, recibir información dirigida a su localización o la visualización de algunos vídeos.
                    <br><br>

                    <p>&nbsp;</p>
                    <h3><strong>ACTUALIZACIONES Y CAMBIOS EN LA POLÍTICA DE PRIVACIDAD/COOKIES:</strong></h3>

                    Las Webs de AICR pueden modificar esta Política de Cookies en función de exigencias legislativas, reglamentarias, o con la finalidad de adaptar dicha política a las instrucciones dictadas por la Agencia Española de Protección de Datos, por ello se aconseja a los Usuarios que la visiten periódicamente.
                    <br><br>
                    Cuando se produzcan cambios significativos en esta Política de Cookies, se comunicarán a los Usuarios bien mediante la web o a través de correo electrónico a los Usuarios registrados.
                </div>
            </div>
        </div>
    </section>
    {% include "footer.html" %}

{% endblock content %}

dissred/content/templates/footer.html
<!--Footer-->
<footer id="footer">
    <div class="container">
        <div class="row-fluid">
            <ul class="legal">
                <li><a href="{% url 'content:legal_advice' %}"> Aviso Legal</a></li>
                <li><a href="{% url 'content:privacy_policy' %}"> Política de Privacidad</a></li>
                <li><a href="{% url 'content:cookies_policy' %}"> Política de Cookies</a></li>
            </ul>
            <!--/Copyright-->

            {% comment %}
            <div class="span5 cp">
                &copy; 2013 <a target="_blank" href="http://shapebootstrap.net/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">ShapeBootstrap</a>. All Rights Reserved.
            </div>
            <div class="span6">
                <ul class="social pull-right">
                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-twitter"></i></a></li>
                    <li><a href="#"><i class="icon-pinterest"></i></a></li>
                    <li><a href="#"><i class="icon-linkedin"></i></a></li>
                    <li><a href="#"><i class="icon-google-plus"></i></a></li>
                    <li><a href="#"><i class="icon-youtube"></i></a></li>
                    <li><a href="#"><i class="icon-tumblr"></i></a></li>
                    <li><a href="#"><i class="icon-dribbble"></i></a></li>
                    <li><a href="#"><i class="icon-rss"></i></a></li>
                    <li><a href="#"><i class="icon-github-alt"></i></a></li>
                    <li><a href="#"><i class="icon-instagram"></i></a></li>
                </ul>
            </div>
            {% endcomment %}


            <div class="span1 gototop-container">
                <a id="gototop" class="gototop pull-right" href="#"><i class="icon-angle-up"></i></a>
            </div>
            <!--/Goto Top-->
        </div>
    </div>
</footer>
<!--/Footer-->

dissred/content/templates/header.html
{% load url from future %}
<!--Header-->
    <header class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <h1 class="title-head"><a href="{% url 'content:home' %}">malagapresupuestosweb.com</a></h1>
                {# <a id="logo" class="pull-left" href="index.html"></a> #}
                <!-- <div class="nav-collapse collapse pull-right">
                    <ul class="nav">
                        <li class="active"><a href="index.html">Home</a></li>
                        <li><a href="about-us.html">About Us</a></li>
                        <li><a href="services.html">Services</a></li>
                        <li><a href="portfolio.html">Portfolio</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages <i class="icon-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="career.html">Career</a></li>
                                <li><a href="blog-item.html">Blog Single</a></li>
                                <li><a href="faq.html">FAQ</a></li>
                                <li><a href="pricing.html">Pricing</a></li>
                                <li><a href="404.html">404</a></li>
                                <li><a href="typography.html">Typography</a></li>
                                <li><a href="registration.html">Registration</a></li>
                                <li class="divider"></li>
                                <li><a href="privacy.html">Privacy Policy</a></li>
                                <li><a href="terms.html">Terms of Use</a></li>
                            </ul>
                        </li>
                        <li><a href="blog.html">Blog</a></li>
                        <li><a href="contact-us.html">Contact</a></li>
                        <li class="login">
                            <a data-toggle="modal" href="#loginForm"><i class="icon-lock"></i></a>
                        </li>
                    </ul>
                </div> --><!--/.nav-collapse -->
            </div>
        </div>
    </header>
    {% if message %}
        <div onclick="$(this).hide()" style="cursor:pointer; background-color: #5bb75b; color: white; font-size: 25px; padding: 23px; text-align: center; width: 100%;" class="message_container">
            <span class="message">{{ message }}</span>
        </div>
    {% endif %}
    {% if form.non_field_errors %}
        <div onclick="$(this).hide()" style="cursor:pointer; background-color: red; color: white; font-size: 25px; padding: 23px; text-align: center; width: 100%;" class="message_container">
            <span class="message">{{ form.non_field_errors }}</span>
        </div>
    {% endif %}

    <!-- /header -->

dissred/content/templates/home.html
{% extends "layout.html" %}

{% block content %}

    {% include "header.html" %}
    {% include "slide_show.html" %}
    {% include "main_info.html" %}
    {% include "services.html" %}
    {% include "recent_works.html" %}
    {# {% include "clients.html" %} #}
    {% include "bottom.html" %}
    {% include "footer.html" %}
    {# {% include "login_form.html" %} #}

{% endblock content %}